### ISSUE TITLE
Ansible group ceph-mds missing

### ISSUE THREAD

**Issue by grawert** [osism/cfg-cookiecutter#154]
The inventory should define a default group `ceph-mds`. Deployment `osism-ceph mdss` without this group is not possible.

**Comment by berendt** [comment]
The MDS service is not always needed and is therefore not available by default.  The group is not missing, it is commented out by default: https://github.com/osism/cfg-cookiecutter/blob/master/cfg-%7B%7Bcookiecutter.project_name%7D%7D/inventory/99-overwrite#L1-L2.
