### ISSUE TITLE
Neutron rpc response timeouts too short

### ISSUE THREAD

**Issue by grawert** [osism/cfg-cookiecutter#174]
These settings should be set by default. We had problems in a customer environment where `openvswitch` flows had not been persisted because of too short timeouts.

`environments/kolla/files/overlays/neutron.conf`:
```
rpc_response_timeout = 600
rpc_conn_pool_size = 120
```

**Comment by berendt** [comment]
Makes sense. Can you prepare a PR?

**Comment by grawert** [comment]
#176
