### ISSUE TITLE
secrets/keepass.kdbx permissions + password

### ISSUE THREAD

**Issue by frosty-geek** [osism/cfg-cookiecutter#175]
Hi all,

secrets/keepass.kdbx gets created with the default umask permissions, which most of the times will result to 0644 and a default permission of 0600 would be preferable. As already mentioned in the README.md the password for this keypass file is a well-known password and it's recommended to change this. It would be nice if the python script would receive the password either from an environment variable or from a cookiecutter variable.

maybe it's also a good idea to change the default permissions of the "secrets" folder to 0700, comments?

Regards,
Ralf

**Comment by berendt** [comment]
From my side, there is nothing against changing this. Are you preparing a PR?

**Comment by frosty-geek** [comment]
I'll try to fix this with my limited python skills #refactoringwelcome ;-)

**Comment by berendt** [comment]
> From my side, there is nothing against changing this. Are you preparing a PR?

We will get that right then ;)

**Comment by berendt** [comment]
> I'll try to fix this with my limited python skills #refactoringwelcome ;-)

We will get that right then ;)
