### ISSUE TITLE
Choosing default for name_servers and ntp_servers not working

### ISSUE THREAD

**Issue by grawert** [osism/cfg-cookiecutter#223]
When hitting enter to use the defaults for `name_servers` and `ntp_servers` following error occurs:

```
name_servers [default]: 
Error: Unable to decode to JSON.
```

Assigning a value works:
```
name_servers [default]: { "values": ["9.9.9.9", "149.112.112.112"] } 
ntp_servers [default]: 
```

Same with `ntp_servers`.

**Comment by berendt** [comment]
This one is related to the following issues/PRs in cookiecutter:

cookiecutter/cookiecutter#1582
cookiecutter/cookiecutter#1562

I created a PR to pin click<8.0.0. Please check again with the new requirements.txt file.

**Comment by grawert** [comment]
Works! OSISM documentation needs to be updated.

**Comment by berendt** [comment]
@grawert Can you please take over with the documentation?
