### ISSUE TITLE
fill in some examples for proxy settings

### ISSUE THREAD

**Issue by muellerbe** [osism/cfg-cookiecutter#269]
fill in the configuration.yml some examples for proxy settings, for operating system and docker

docker_configure_proxy: true
docker_proxy_http: "<fillin>"
docker_proxy_https: "{{ docker_proxy_http }}"
docker_proxy_no_proxy:
  - localhost
  - 127.0.0.1

proxy_proxies:
  http: "<fillin>"
  https: "<fillin>"
proxy_package_manager: no
proxy_no_proxy_extra:
  - localhost
  - 127.0.0.1

one more tweak could be, to fill in all possible ip and fqdn variables like

kolla_internal_fqdn: 
kolla_external_fqdn:
kolla_internal_vip_address: 
kolla_external_vip_address:

=>
proxy_no_proxy_extra:
  - 127.0.0.1
  - localhost
  - "{{ kolla_internal_vip_address }}"
  - "{{ kolla_internal_fqdn }}"
docker_proxy_no_proxy:
  - 127.0.0.1
  - localhost
  - "{{ kolla_internal_vip_address }}"
  - "{{ kolla_internal_fqdn }}"

**Comment by berendt** [comment]
Cookiecutter is intended to provide a minimal working configuration and does not include examples. For examples the documentation is available.
