### ISSUE TITLE
osism releases

### ISSUE THREAD

**Issue by frosty-geek** [osism/cfg-cookiecutter#323]
https://github.com/osism/cfg-cookiecutter/blob/b83a5ea3d6157adc3d604874ca7efb982c08ee93/cookiecutter.json#L21

should this reference to 3.1.0 as current "stable"? or will "latest" reflect "stable" (=3.1.0 atm)?

ref: https://release.osism.tech/

**Comment by berendt** [comment]
In Cookiecutter, latest is referenced by default. If you want to use e.g. 3.1.0 you have to set this version accordingly.
