### ISSUE TITLE
Definition of 'operator_user' and 'operator_group' is missing in environments/configuration.yml

### ISSUE THREAD

**Issue by grawert** [osism/cfg-cookiecutter#74]
Both variables are missing at https://github.com/osism/cfg-cookiecutter/blob/19db8e9570f462f4ddc715cce4ae412629f04b25/cfg-%7B%7Bcookiecutter.project_name%7D%7D/environments/configuration.yml#L48

operator_user: dragon
operator_group: dragon

**Comment by berendt** [comment]
Moved to https://github.com/osism/osism-ansible/blob/master/group_vars/all/generic.yml#L105-L109.
